# Nav2 Localisation + Path Planning

amcl:
  ros__parameters:
    use_sim_time: True
    min_particles: 500
    max_particles: 2000
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    scan_topic: '/scan'
    laser_model_type: "likelihood_field"
    global_frame_id: map
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "maps/warehouse_map.yaml"

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: "navigate_w_replanning.xml"

lifecycle_manager:
  ros__parameters:
    node_names:
      - map_server
      - amcl
      - planner_server
      - controller_server
      - bt_navigator

      