boxes:
  - tag: box1
  - tag: box2
  - tag: box3
  - tag: box4

shelves:
  - {x: 0, y: 0, z: 1.2}  # shelf_box1
  - {x: 3, y: 2, z: 1.2}  # shelf_box2
  - {x: 6, y: 4, z: 1.2}  # shelf_box3
  - {x: 6, y: 2, z: 0.2}  # extra shelf for box4
pick_locations:
  - {x: 1, y: 1, z: 0.0}  # pick_box1
  - {x: 4, y: 3, z: 0.0}  # pick_box2
  - {x: 7, y: 5, z: 0.0}  # pick_box3
  - {x: 1, y: 5, z: 0.0}  # pick_box4
place_locations:
  - {x: 2, y: 1, z: 0.0}  # place_box1
  - {x: 5, y: 3, z: 0.0}  # place_box2
  - {x: 8, y: 5, z: 0.0}  # place_box3  